services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_service
      POSTGRES_USER_FILE: /run/secrets/spring_datasource_username
      POSTGRES_PASSWORD_FILE: /run/secrets/spring_datasource_password
    secrets:
      - spring_datasource_username
      - spring_datasource_password
    ports:
      - "5434:5432"

  app:
    image: blogging-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_service
      SPRING_DATASOURCE_USERNAME_FILE: /run/secrets/spring_datasource_username
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/spring_datasource_password
      TOKEN_SIGNING_KEY_FILE: /run/secrets/token_signing_key
    secrets:
      - spring_datasource_username
      - spring_datasource_password
      - token_signing_key
    ports:
      - "8082:8082"
    depends_on:
      - db


  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

secrets:
  spring_datasource_username:
    file: ./secrets/spring_datasource_username.txt
  spring_datasource_password:
    file: ./secrets/spring_datasource_password.txt
  token_signing_key:
    file: ./secrets/token_signing_key.txt