services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"

  app:
    image: blogging-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
    depends_on:
      - db

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080