services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080